[package]
name = "rs_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json", "blocking"] }
