[package]
name = "rs_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = "1"
serde_derive = "1"
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
ratatui = "0.29"
crossterm = "0.28"
